/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpclient;

import javax.swing.*;
import javax.swing.text.DefaultCaret;
import java.awt.*;
import java.net.Socket;

/**
 *
 * @author NannaJosefine
 */
public class TabHolder extends javax.swing.JPanel {

    public JFrame terminalFrame = new JFrame();
    public Socket socket;
    public FTPConnection ftp = new FTPConnection();
    public ZyboConnect zybo;
    public JPanel jPanel = new JPanel();
    public JTextArea jTextArea = new JTextArea();
    public JLayeredPane layerManager = new JLayeredPane();
    //public JScrollPane jScrollPane = new JScrollPane(jTextArea, JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
    public JScrollPane jScrollPane = new JScrollPane();
    //public FTPTerminal fTerminal = new FTPTerminal();
    
    /**
     * Creates new form TabHolder
     */
    public TabHolder() {
        initComponents();
        fTPMenu1.owner = this;
        logIn1.owner = this;
        mainMenu1.owner = this;
        retreive1.owner = this;
        sensorEcho1.owner = this;
        sensorInfo1.owner = this;
        sensorLogIn1.owner = this;
        sensorMenu2.owner = this;
        sensorStart1.owner = this;
        sensorStop1.owner = this;
        sensorTerminal1.owner = this;
        terminal1.owner = this;
        uploadFile1.owner = this;
        sensorSampleRate1.owner = this;
        
        terminalFrame.setLayout(new BorderLayout());
        terminalFrame.setTitle("Terminal");
        terminalFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        terminalFrame.setPreferredSize(new Dimension(400,400));
        terminalFrame.setLocation(800, 200);
        terminalFrame.add(layerManager, BorderLayout.CENTER);
        terminalFrame.setUndecorated(false);
        terminalFrame.setAlwaysOnTop(false);
        
        jPanel.setBounds(0, 0, Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);
        //jPanel.setBounds(0, 0, 800, 600);
        jPanel.setBackground(Color.black);

        jTextArea.setBounds(10, 10, Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height);
        //jTextArea.setBounds(0, 0, 800, 600);
        jTextArea.setBackground(Color.BLACK);
        jTextArea.setForeground(Color.white);
        jTextArea.setEditable(false);
        
        DefaultCaret caret = (DefaultCaret)jTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
        
        jScrollPane.setBounds(0, 0, 800, 600);
        jScrollPane.setAutoscrolls(true);
        jScrollPane.add(jPanel);
        
        //layerManager.add(jPanel, 1, 0);
        layerManager.add(jTextArea, 2, 0);
        layerManager.add(jScrollPane,1, 0);
        
        terminalFrame.pack();
        terminalFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        mainMenu1 = new ftpclient.MainMenu();
        logIn1 = new ftpclient.FTPLogIn();
        sensorLogIn1 = new ftpclient.SensorLogIn();
        fTPMenu1 = new ftpclient.FTPMenu();
        sensorMenu2 = new ftpclient.SensorMenu();
        terminal1 = new ftpclient.FTPTerminal();
        retreive1 = new ftpclient.FTPRetreive();
        uploadFile1 = new ftpclient.FTPUploadFile();
        sensorTerminal1 = new ftpclient.SensorTerminal();
        sensorStop1 = new ftpclient.SensorStop();
        sensorEcho1 = new ftpclient.SensorEcho();
        sensorInfo1 = new ftpclient.SensorInfo();
        sensorStart1 = new ftpclient.SensorStart();
        sensorSampleRate1 = new ftpclient.SensorSampleRate();

        jTabbedPane1.addTab("MainMenu", mainMenu1);
        jTabbedPane1.addTab("FTPLogIn", logIn1);
        jTabbedPane1.addTab("SensorLogIn", sensorLogIn1);
        jTabbedPane1.addTab("FTPMenu", fTPMenu1);
        jTabbedPane1.addTab("SensorMenu", sensorMenu2);
        jTabbedPane1.addTab("FTPTerminal", terminal1);
        jTabbedPane1.addTab("Retreive file", retreive1);
        jTabbedPane1.addTab("Upload file", uploadFile1);
        jTabbedPane1.addTab("SensorTerminal", sensorTerminal1);
        jTabbedPane1.addTab("SensorStop", sensorStop1);
        jTabbedPane1.addTab("Echo", sensorEcho1);
        jTabbedPane1.addTab("SensorInfo", sensorInfo1);
        jTabbedPane1.addTab("SensorStart", sensorStart1);
        jTabbedPane1.addTab("SampleRate", sensorSampleRate1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ftpclient.FTPMenu fTPMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private ftpclient.FTPLogIn logIn1;
    private ftpclient.MainMenu mainMenu1;
    private ftpclient.FTPRetreive retreive1;
    private ftpclient.SensorEcho sensorEcho1;
    private ftpclient.SensorInfo sensorInfo1;
    private ftpclient.SensorLogIn sensorLogIn1;
    private ftpclient.SensorMenu sensorMenu2;
    private ftpclient.SensorSampleRate sensorSampleRate1;
    private ftpclient.SensorStart sensorStart1;
    private ftpclient.SensorStop sensorStop1;
    private ftpclient.SensorTerminal sensorTerminal1;
    private ftpclient.FTPTerminal terminal1;
    private ftpclient.FTPUploadFile uploadFile1;
    // End of variables declaration//GEN-END:variables

    void changeTab(int tabNumber)
    {
        System.out.println("Shifting to tab "+tabNumber);
        jTabbedPane1.setSelectedIndex(tabNumber);
    }
    
    public void updateTerminalText(String text) {
            SwingUtilities.invokeLater(() -> jTextArea.append(text+"\n"));
            terminalFrame.repaint();
        }
}
